model: ssf2020
dataset: /data/ssd/liuchaolei/vimeo_septuplet
epochs: 100
learning_rate: 0.0001
num_workers: 4
lmbda: 0.01
batch_size: 16
test_batch_size: 64
aux_learning_rate: 0.001
patch_size: 256
cuda: True
save: True
seed: 1.0
clip_max_norm: 1.0
checkpoint: ~